name: On merge
on:
  push:
    branches:
      - main
jobs:
  container:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
            registry: https://trialk033s3.jfrog.io/docker-trial
            username: jean@parpaillon.info
            password: ${{ secrets.JFROG_DOCKER_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
            context: .
            push: true
            tags: trialk033s3.jfrog.io/docker-trial/tuto_live_jean:latest, trialk033s3.jfrog.io/docker-trial/tuto_live_jean:${{ github.ref_name }}
  deploy:
      runs-on: self-hosted
      needs: container
      steps:
        - name: Deploy to Docker
          run: |
            docker stop tuto_live || true
            docker rm tuto_live || true
            docker run --name tuto_live -p 4000:4000 -d trialk033s3.jfrog.io/docker-trial/tuto_live_jean:latest
